spring.application.name=MessReduction
server.port=8080

# DB connect
spring.datasource.url=jdbc:postgresql://ep-snowy-leaf-aormjz9l-pooler.c-2.ap-southeast-1.aws.neon.tech/MessReduction?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_70OsEwvkWlDj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#JWT Configuration
jwt.secret=MySecretKeyForJWTTokenGenerationMessReductionApp2024
jwt.expiration=86400000